# Generated by Django 5.1.7 on 2025-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recteur', 'Recteur'), ('comptable', 'Comptable'), ('rh', 'Ressources Humaines'), ('technique', 'Technique'), ('qualite', 'Qualité'), ('doyen', 'Doyen'), ('academique', 'Académique'), ('employe', 'Employé'), ('etudiant', 'Etudiant'), ('enseignants', 'Eseignants')], default='employe', max_length=20),
        ),
    ]
